repos:
  - repo: https://github.com/pre-commit/pre-commit-hooks
    rev: v4.5.0
    hooks:
      - id: trailing-whitespace
        stages: [pre-commit]
      - id: end-of-file-fixer
        stages: [pre-commit]
      - id: check-yaml
        stages: [pre-commit]
      - id: detect-private-key
        stages: [pre-commit]
      - id: no-commit-to-branch
        args: ["--branch", "main", "--branch", "release", "--branch", "staging"]

  - repo: https://github.com/Weburz/crisp
    rev: v0.1.4
    hooks:
      - id: crisp
        name: lint git-commit messages
